"use client";

import { usePathname } from "next/navigation";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";
import "@/lib/fontawesome";
import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isAdminRoute = pathname?.startsWith("/admin");

  return (
    <html lang="en">
      <body className="relative h-full w-full bg-[url('/images/bg3.jpg')]  bg-cover bg-center z-100">
        <div className="bg-black opacity-50 absolute h-[100%] w-full z-0" />
        <div className="z-10 relative">
          {!isAdminRoute && <Navbar />}
          {children}
          <Toaster />
          <Footer />
        </div>
      </body>
    </html>
  );
}
